# Measurement Parameters Survey for S0_SampleRegister 

machine_IP = ' 192.168.1.10 ' # type in str 

cool_down_date = ' 2024/11/12 ' # type in str 

cool_down_dr = ' dr2 ' # type in str 

sample_name = ' 5Q4C_Test ' # type in str 

