SurveyUniqueName = "ExpParasSurvey"   # Generated by FBI, please do NOT change it.
ConfigUniqueName = "ExpConfigs"       # The folder contains hardware configs which you upload to server should have this keyword, like 'Test_ExpConfigs', 'My_QM_ExpConfigs', ...
IdentityUniqueName = "WhoDoWhat"
OneshotUniqueVariableName = "target_qs"
data_file_fmt:list = ["nc"]           # When queue out, Queuer need to know what file needs to be analyzed
survey_file_fmt:str = 'toml'

if __name__ == "__main__":
    Correct_example = 'Test_ExpConfigs'
    print("Correct name: ",ConfigUniqueName.lower() in Correct_example.lower())
    Incorrect_example = 'Test_Exp_Config'
    print("Inorrect name: ",ConfigUniqueName.lower() in Incorrect_example.lower())